name: CI
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build Project (Import Check)
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Resources
        run: godot --headless --path workspace --editor --quit
